services:
  db:
    image: postgres:15
    container_name: test-postgres
    environment:
      POSTGRES_DB: ${DATABASE_DBNAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./test_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: test-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: [ "redis-server", "--requirepass", "your_secure_password" ]
    environment:
      - TZ=UTC

volumes:
  redis_data:
    driver: local