basePath: /api/v1
definitions:
  http.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  middleware.ValidationErrorResponse:
    properties:
      error:
        properties:
          code:
            type: integer
          fields:
            additionalProperties:
              type: string
            description: Поля с ошибками
            type: object
          message:
            type: string
        type: object
    type: object
  models.InputRefresh:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  models.SignInInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  models.Tokens:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      password:
        maxLength: 16
        minLength: 8
        type: string
      username:
        maxLength: 20
        minLength: 5
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.UserIdResponse:
    properties:
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для авторизации и аутентификации.
  title: Auth
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Logs in a user and returns access and refresh tokens
      parameters:
      - description: Login credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: Access and refresh tokens
          schema:
            $ref: '#/definitions/models.Tokens'
        "400":
          description: Invalid input format
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
        "403":
          description: invalid username or password
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
      summary: User login
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refreshes the access token using a valid refresh token
      parameters:
      - description: Refresh token
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.InputRefresh'
      produces:
      - application/json
      responses:
        "200":
          description: New access and refresh tokens
          schema:
            $ref: '#/definitions/models.Tokens'
        "400":
          description: Invalid input format
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
        "401":
          description: Unauthorized or invalid refresh token
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
      summary: Refresh access token
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account
      parameters:
      - description: User details
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: User ID
          schema:
            $ref: '#/definitions/models.UserIdResponse'
        "400":
          description: Invalid input format or validation errors
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
      summary: Register a new user
      tags:
      - auth
  /auth/revoke-token:
    delete:
      consumes:
      - application/json
      description: Revokes the specified refresh token
      parameters:
      - description: Refresh token
        in: query
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Token revoked successfully
          schema:
            $ref: '#/definitions/http.SuccessResponse'
        "400":
          description: Invalid input format
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/middleware.ValidationErrorResponse'
      summary: Revoke refresh token
      tags:
      - auth
swagger: "2.0"
